// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dataRequest.proto

package databaseRpcDemo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	SqlStatement         string   `protobuf:"bytes,6,opt,name=sqlStatement,proto3" json:"sqlStatement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_0f474c01465d8734, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *Request) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Request) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Request) GetSqlStatement() string {
	if m != nil {
		return m.SqlStatement
	}
	return ""
}

type Response struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Dataset              *DataSet `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_0f474c01465d8734, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Response) GetDataset() *DataSet {
	if m != nil {
		return m.Dataset
	}
	return nil
}

type DataSet struct {
	Tables               []*DataTable `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DataSet) Reset()         { *m = DataSet{} }
func (m *DataSet) String() string { return proto.CompactTextString(m) }
func (*DataSet) ProtoMessage()    {}
func (*DataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_0f474c01465d8734, []int{2}
}
func (m *DataSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSet.Unmarshal(m, b)
}
func (m *DataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSet.Marshal(b, m, deterministic)
}
func (dst *DataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSet.Merge(dst, src)
}
func (m *DataSet) XXX_Size() int {
	return xxx_messageInfo_DataSet.Size(m)
}
func (m *DataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSet.DiscardUnknown(m)
}

var xxx_messageInfo_DataSet proto.InternalMessageInfo

func (m *DataSet) GetTables() []*DataTable {
	if m != nil {
		return m.Tables
	}
	return nil
}

type DataTable struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns              []*DataColumn `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows                 []*DataRow    `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DataTable) Reset()         { *m = DataTable{} }
func (m *DataTable) String() string { return proto.CompactTextString(m) }
func (*DataTable) ProtoMessage()    {}
func (*DataTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_0f474c01465d8734, []int{3}
}
func (m *DataTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTable.Unmarshal(m, b)
}
func (m *DataTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTable.Marshal(b, m, deterministic)
}
func (dst *DataTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTable.Merge(dst, src)
}
func (m *DataTable) XXX_Size() int {
	return xxx_messageInfo_DataTable.Size(m)
}
func (m *DataTable) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTable.DiscardUnknown(m)
}

var xxx_messageInfo_DataTable proto.InternalMessageInfo

func (m *DataTable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataTable) GetColumns() []*DataColumn {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *DataTable) GetRows() []*DataRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type DataColumn struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DbType               string   `protobuf:"bytes,3,opt,name=dbType,proto3" json:"dbType,omitempty"`
	DbSize               int32    `protobuf:"varint,4,opt,name=dbSize,proto3" json:"dbSize,omitempty"`
	Precision            int32    `protobuf:"varint,5,opt,name=precision,proto3" json:"precision,omitempty"`
	Index                int32    `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataColumn) Reset()         { *m = DataColumn{} }
func (m *DataColumn) String() string { return proto.CompactTextString(m) }
func (*DataColumn) ProtoMessage()    {}
func (*DataColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_0f474c01465d8734, []int{4}
}
func (m *DataColumn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataColumn.Unmarshal(m, b)
}
func (m *DataColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataColumn.Marshal(b, m, deterministic)
}
func (dst *DataColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataColumn.Merge(dst, src)
}
func (m *DataColumn) XXX_Size() int {
	return xxx_messageInfo_DataColumn.Size(m)
}
func (m *DataColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_DataColumn.DiscardUnknown(m)
}

var xxx_messageInfo_DataColumn proto.InternalMessageInfo

func (m *DataColumn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataColumn) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DataColumn) GetDbType() string {
	if m != nil {
		return m.DbType
	}
	return ""
}

func (m *DataColumn) GetDbSize() int32 {
	if m != nil {
		return m.DbSize
	}
	return 0
}

func (m *DataColumn) GetPrecision() int32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *DataColumn) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type DataRow struct {
	Values               []*any.Any `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataRow) Reset()         { *m = DataRow{} }
func (m *DataRow) String() string { return proto.CompactTextString(m) }
func (*DataRow) ProtoMessage()    {}
func (*DataRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_0f474c01465d8734, []int{5}
}
func (m *DataRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRow.Unmarshal(m, b)
}
func (m *DataRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRow.Marshal(b, m, deterministic)
}
func (dst *DataRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRow.Merge(dst, src)
}
func (m *DataRow) XXX_Size() int {
	return xxx_messageInfo_DataRow.Size(m)
}
func (m *DataRow) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRow.DiscardUnknown(m)
}

var xxx_messageInfo_DataRow proto.InternalMessageInfo

func (m *DataRow) GetValues() []*any.Any {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "databaseRpcDemo.Request")
	proto.RegisterType((*Response)(nil), "databaseRpcDemo.Response")
	proto.RegisterType((*DataSet)(nil), "databaseRpcDemo.DataSet")
	proto.RegisterType((*DataTable)(nil), "databaseRpcDemo.DataTable")
	proto.RegisterType((*DataColumn)(nil), "databaseRpcDemo.DataColumn")
	proto.RegisterType((*DataRow)(nil), "databaseRpcDemo.DataRow")
}

func init() { proto.RegisterFile("dataRequest.proto", fileDescriptor_dataRequest_0f474c01465d8734) }

var fileDescriptor_dataRequest_0f474c01465d8734 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x55, 0xba, 0x9b, 0x6c, 0x33, 0x45, 0x42, 0x58, 0x15, 0x32, 0x0b, 0x87, 0x55, 0x4e, 0x7b,
	0xa8, 0x52, 0x29, 0x08, 0x71, 0xe2, 0x80, 0xe8, 0x85, 0xeb, 0x6c, 0xc5, 0xdd, 0xd9, 0x0c, 0x55,
	0xa4, 0xc4, 0x4e, 0x6d, 0xa7, 0x61, 0x39, 0xf3, 0x23, 0xf8, 0x0b, 0xfc, 0x4b, 0xe4, 0x8f, 0x6c,
	0x05, 0xca, 0x6d, 0xde, 0xf3, 0x9b, 0xf1, 0xf3, 0x1b, 0xc3, 0xab, 0x46, 0x58, 0x81, 0xf4, 0x38,
	0x92, 0xb1, 0xe5, 0xa0, 0x95, 0x55, 0xec, 0xa5, 0xa3, 0x6a, 0x61, 0x08, 0x87, 0xe3, 0x1d, 0xf5,
	0x6a, 0xfb, 0xe6, 0x41, 0xa9, 0x87, 0x8e, 0x6e, 0xfd, 0x71, 0x3d, 0x7e, 0xbf, 0x15, 0xf2, 0x14,
	0xb4, 0xc5, 0x9f, 0x04, 0x36, 0xb1, 0x9b, 0xbd, 0x86, 0xcc, 0x90, 0x7e, 0x22, 0xcd, 0x93, 0x5d,
	0xb2, 0xcf, 0x31, 0x22, 0xc6, 0x60, 0x3d, 0x28, 0x6d, 0xf9, 0xc5, 0x2e, 0xd9, 0xa7, 0xe8, 0x6b,
	0xb6, 0x85, 0xcb, 0xf9, 0x16, 0xbe, 0xf2, 0xea, 0x33, 0x76, 0x73, 0x46, 0x43, 0xfa, 0x6b, 0xc3,
	0xd7, 0x61, 0x4e, 0x40, 0xae, 0x67, 0x10, 0xc6, 0x4c, 0x4a, 0x37, 0x3c, 0x0d, 0x3d, 0x33, 0x66,
	0x05, 0xbc, 0x30, 0x8f, 0xdd, 0xc1, 0x0a, 0x4b, 0x3d, 0x49, 0xcb, 0x33, 0x7f, 0xfe, 0x0f, 0x57,
	0x7c, 0x83, 0x4b, 0x24, 0x33, 0x28, 0x19, 0xee, 0xd0, 0x64, 0xc6, 0xce, 0xce, 0x5e, 0x03, 0x62,
	0x15, 0x6c, 0x9c, 0x0f, 0x43, 0xc1, 0xee, 0x55, 0xc5, 0xcb, 0xff, 0xd2, 0x28, 0xef, 0x84, 0x15,
	0x07, 0xb2, 0x38, 0x0b, 0x8b, 0x4f, 0xb0, 0x89, 0x1c, 0xab, 0x20, 0xb3, 0xa2, 0xee, 0xc8, 0xf0,
	0x64, 0xb7, 0xda, 0x5f, 0x55, 0xdb, 0xc5, 0xee, 0x7b, 0x27, 0xc1, 0xa8, 0x2c, 0x7e, 0x25, 0x90,
	0x9f, 0x59, 0x17, 0x96, 0x14, 0x3d, 0x45, 0x5b, 0xbe, 0x66, 0x1f, 0x60, 0x73, 0x54, 0xdd, 0xd8,
	0x4b, 0xc3, 0x2f, 0xfc, 0xd8, 0xb7, 0x8b, 0x63, 0xbf, 0x78, 0x0d, 0xce, 0x5a, 0x76, 0x03, 0x6b,
	0xad, 0x26, 0xc3, 0x57, 0xbe, 0x67, 0xf9, 0x21, 0xa8, 0x26, 0xf4, 0xaa, 0xe2, 0x77, 0x02, 0xf0,
	0x3c, 0x65, 0xd1, 0x07, 0x83, 0xb5, 0x3d, 0x0d, 0xe4, 0x93, 0xc9, 0xd1, 0xd7, 0x2e, 0xc8, 0xa6,
	0xbe, 0x77, 0x6c, 0x58, 0x63, 0x44, 0x81, 0x3f, 0xb4, 0x3f, 0xc9, 0x2f, 0x31, 0xc5, 0x88, 0xd8,
	0x3b, 0xc8, 0x07, 0x4d, 0xc7, 0xd6, 0xb4, 0x4a, 0xfa, 0x2d, 0xa6, 0xf8, 0x4c, 0xb0, 0x6b, 0x48,
	0x5b, 0xd9, 0xd0, 0x0f, 0xbf, 0xbf, 0x14, 0x03, 0x28, 0x3e, 0x86, 0x80, 0x51, 0x4d, 0xec, 0x06,
	0xb2, 0x27, 0xd1, 0x8d, 0xe7, 0x80, 0xaf, 0xcb, 0xf0, 0x37, 0xcb, 0xf9, 0x6f, 0x96, 0x9f, 0xe5,
	0x09, 0xa3, 0xa6, 0xce, 0x3c, 0xfb, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0x26, 0xd7,
	0xec, 0xe5, 0x02, 0x00, 0x00,
}
