// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dataRequest.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DBRequest struct {
	// Token will be used to identify the server connection info
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Or the server connection info was given in the DbRequest
	ServerInfo *ServerInfo `protobuf:"bytes,2,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	// The script name to locate a DB script for execution
	Script string `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	// The plain text sql statement
	SqlStatement string `protobuf:"bytes,4,opt,name=sqlStatement,proto3" json:"sqlStatement,omitempty"`
	// Parameter list
	Parameters           []*DBParameter `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DBRequest) Reset()         { *m = DBRequest{} }
func (m *DBRequest) String() string { return proto.CompactTextString(m) }
func (*DBRequest) ProtoMessage()    {}
func (*DBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b3a812fe340b910b, []int{0}
}
func (m *DBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBRequest.Unmarshal(m, b)
}
func (m *DBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBRequest.Marshal(b, m, deterministic)
}
func (dst *DBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBRequest.Merge(dst, src)
}
func (m *DBRequest) XXX_Size() int {
	return xxx_messageInfo_DBRequest.Size(m)
}
func (m *DBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DBRequest proto.InternalMessageInfo

func (m *DBRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DBRequest) GetServerInfo() *ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

func (m *DBRequest) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *DBRequest) GetSqlStatement() string {
	if m != nil {
		return m.SqlStatement
	}
	return ""
}

func (m *DBRequest) GetParameters() []*DBParameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type DBParameter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DbType               string   `protobuf:"bytes,2,opt,name=dbType,proto3" json:"dbType,omitempty"`
	DbLength             int64    `protobuf:"varint,3,opt,name=dbLength,proto3" json:"dbLength,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBParameter) Reset()         { *m = DBParameter{} }
func (m *DBParameter) String() string { return proto.CompactTextString(m) }
func (*DBParameter) ProtoMessage()    {}
func (*DBParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b3a812fe340b910b, []int{1}
}
func (m *DBParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBParameter.Unmarshal(m, b)
}
func (m *DBParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBParameter.Marshal(b, m, deterministic)
}
func (dst *DBParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBParameter.Merge(dst, src)
}
func (m *DBParameter) XXX_Size() int {
	return xxx_messageInfo_DBParameter.Size(m)
}
func (m *DBParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_DBParameter.DiscardUnknown(m)
}

var xxx_messageInfo_DBParameter proto.InternalMessageInfo

func (m *DBParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DBParameter) GetDbType() string {
	if m != nil {
		return m.DbType
	}
	return ""
}

func (m *DBParameter) GetDbLength() int64 {
	if m != nil {
		return m.DbLength
	}
	return 0
}

func (m *DBParameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ServerInfo struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b3a812fe340b910b, []int{2}
}
func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (dst *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(dst, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *ServerInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerInfo) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ServerInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ServerInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type DBResponse struct {
	Succeeded bool   `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// For execute scalar operation
	ScalarValue *DBScalarValue `protobuf:"bytes,3,opt,name=scalarValue,proto3" json:"scalarValue,omitempty"`
	// For execute none query operation
	RowEffected int64 `protobuf:"varint,4,opt,name=rowEffected,proto3" json:"rowEffected,omitempty"`
	// For execute execute dataset operation
	Dataset              *DataSet `protobuf:"bytes,5,opt,name=dataset,proto3" json:"dataset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBResponse) Reset()         { *m = DBResponse{} }
func (m *DBResponse) String() string { return proto.CompactTextString(m) }
func (*DBResponse) ProtoMessage()    {}
func (*DBResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b3a812fe340b910b, []int{3}
}
func (m *DBResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBResponse.Unmarshal(m, b)
}
func (m *DBResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBResponse.Marshal(b, m, deterministic)
}
func (dst *DBResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBResponse.Merge(dst, src)
}
func (m *DBResponse) XXX_Size() int {
	return xxx_messageInfo_DBResponse.Size(m)
}
func (m *DBResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DBResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DBResponse proto.InternalMessageInfo

func (m *DBResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *DBResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DBResponse) GetScalarValue() *DBScalarValue {
	if m != nil {
		return m.ScalarValue
	}
	return nil
}

func (m *DBResponse) GetRowEffected() int64 {
	if m != nil {
		return m.RowEffected
	}
	return 0
}

func (m *DBResponse) GetDataset() *DataSet {
	if m != nil {
		return m.Dataset
	}
	return nil
}

type DataSet struct {
	Tables               []*DataTable `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DataSet) Reset()         { *m = DataSet{} }
func (m *DataSet) String() string { return proto.CompactTextString(m) }
func (*DataSet) ProtoMessage()    {}
func (*DataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b3a812fe340b910b, []int{4}
}
func (m *DataSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSet.Unmarshal(m, b)
}
func (m *DataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSet.Marshal(b, m, deterministic)
}
func (dst *DataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSet.Merge(dst, src)
}
func (m *DataSet) XXX_Size() int {
	return xxx_messageInfo_DataSet.Size(m)
}
func (m *DataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSet.DiscardUnknown(m)
}

var xxx_messageInfo_DataSet proto.InternalMessageInfo

func (m *DataSet) GetTables() []*DataTable {
	if m != nil {
		return m.Tables
	}
	return nil
}

type DataTable struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Column definitions of this table
	Columns []*DataColumn `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Rows in this table
	Rows                 []*DataRow `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataTable) Reset()         { *m = DataTable{} }
func (m *DataTable) String() string { return proto.CompactTextString(m) }
func (*DataTable) ProtoMessage()    {}
func (*DataTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b3a812fe340b910b, []int{5}
}
func (m *DataTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTable.Unmarshal(m, b)
}
func (m *DataTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTable.Marshal(b, m, deterministic)
}
func (dst *DataTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTable.Merge(dst, src)
}
func (m *DataTable) XXX_Size() int {
	return xxx_messageInfo_DataTable.Size(m)
}
func (m *DataTable) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTable.DiscardUnknown(m)
}

var xxx_messageInfo_DataTable proto.InternalMessageInfo

func (m *DataTable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataTable) GetColumns() []*DataColumn {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *DataTable) GetRows() []*DataRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type DataColumn struct {
	// Zero based column index in the DB record set
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// The name of the column
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The db type of the column
	DbType string `protobuf:"bytes,3,opt,name=dbType,proto3" json:"dbType,omitempty"`
	// The db size
	Length int64 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	// golang type
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// For decimal numeric type
	Precision int64 `protobuf:"varint,6,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale     int64 `protobuf:"varint,7,opt,name=scale,proto3" json:"scale,omitempty"`
	// Indicate if the column is nullable
	Nullable             bool     `protobuf:"varint,8,opt,name=nullable,proto3" json:"nullable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataColumn) Reset()         { *m = DataColumn{} }
func (m *DataColumn) String() string { return proto.CompactTextString(m) }
func (*DataColumn) ProtoMessage()    {}
func (*DataColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b3a812fe340b910b, []int{6}
}
func (m *DataColumn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataColumn.Unmarshal(m, b)
}
func (m *DataColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataColumn.Marshal(b, m, deterministic)
}
func (dst *DataColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataColumn.Merge(dst, src)
}
func (m *DataColumn) XXX_Size() int {
	return xxx_messageInfo_DataColumn.Size(m)
}
func (m *DataColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_DataColumn.DiscardUnknown(m)
}

var xxx_messageInfo_DataColumn proto.InternalMessageInfo

func (m *DataColumn) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DataColumn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataColumn) GetDbType() string {
	if m != nil {
		return m.DbType
	}
	return ""
}

func (m *DataColumn) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *DataColumn) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DataColumn) GetPrecision() int64 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *DataColumn) GetScale() int64 {
	if m != nil {
		return m.Scale
	}
	return 0
}

func (m *DataColumn) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

type DataRow struct {
	Values               []*DBValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataRow) Reset()         { *m = DataRow{} }
func (m *DataRow) String() string { return proto.CompactTextString(m) }
func (*DataRow) ProtoMessage()    {}
func (*DataRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b3a812fe340b910b, []int{7}
}
func (m *DataRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRow.Unmarshal(m, b)
}
func (m *DataRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRow.Marshal(b, m, deterministic)
}
func (dst *DataRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRow.Merge(dst, src)
}
func (m *DataRow) XXX_Size() int {
	return xxx_messageInfo_DataRow.Size(m)
}
func (m *DataRow) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRow.DiscardUnknown(m)
}

var xxx_messageInfo_DataRow proto.InternalMessageInfo

func (m *DataRow) GetValues() []*DBValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBValue struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBValue) Reset()         { *m = DBValue{} }
func (m *DBValue) String() string { return proto.CompactTextString(m) }
func (*DBValue) ProtoMessage()    {}
func (*DBValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b3a812fe340b910b, []int{8}
}
func (m *DBValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBValue.Unmarshal(m, b)
}
func (m *DBValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBValue.Marshal(b, m, deterministic)
}
func (dst *DBValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBValue.Merge(dst, src)
}
func (m *DBValue) XXX_Size() int {
	return xxx_messageInfo_DBValue.Size(m)
}
func (m *DBValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DBValue.DiscardUnknown(m)
}

var xxx_messageInfo_DBValue proto.InternalMessageInfo

func (m *DBValue) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DBScalarValue struct {
	Type                 *DataColumn `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                *DBValue    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DBScalarValue) Reset()         { *m = DBScalarValue{} }
func (m *DBScalarValue) String() string { return proto.CompactTextString(m) }
func (*DBScalarValue) ProtoMessage()    {}
func (*DBScalarValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b3a812fe340b910b, []int{9}
}
func (m *DBScalarValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBScalarValue.Unmarshal(m, b)
}
func (m *DBScalarValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBScalarValue.Marshal(b, m, deterministic)
}
func (dst *DBScalarValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBScalarValue.Merge(dst, src)
}
func (m *DBScalarValue) XXX_Size() int {
	return xxx_messageInfo_DBScalarValue.Size(m)
}
func (m *DBScalarValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DBScalarValue.DiscardUnknown(m)
}

var xxx_messageInfo_DBScalarValue proto.InternalMessageInfo

func (m *DBScalarValue) GetType() *DataColumn {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *DBScalarValue) GetValue() *DBValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*DBRequest)(nil), "proto.DBRequest")
	proto.RegisterType((*DBParameter)(nil), "proto.DBParameter")
	proto.RegisterType((*ServerInfo)(nil), "proto.ServerInfo")
	proto.RegisterType((*DBResponse)(nil), "proto.DBResponse")
	proto.RegisterType((*DataSet)(nil), "proto.DataSet")
	proto.RegisterType((*DataTable)(nil), "proto.DataTable")
	proto.RegisterType((*DataColumn)(nil), "proto.DataColumn")
	proto.RegisterType((*DataRow)(nil), "proto.DataRow")
	proto.RegisterType((*DBValue)(nil), "proto.DBValue")
	proto.RegisterType((*DBScalarValue)(nil), "proto.DBScalarValue")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteDBServiceClient is the client API for RemoteDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteDBServiceClient interface {
	ExecuteNoneQuery(ctx context.Context, in *DBRequest, opts ...grpc.CallOption) (*DBResponse, error)
	ExecuteScalar(ctx context.Context, in *DBRequest, opts ...grpc.CallOption) (*DBResponse, error)
	ExecuteDataSet(ctx context.Context, in *DBRequest, opts ...grpc.CallOption) (*DBResponse, error)
}

type remoteDBServiceClient struct {
	cc *grpc.ClientConn
}

func NewRemoteDBServiceClient(cc *grpc.ClientConn) RemoteDBServiceClient {
	return &remoteDBServiceClient{cc}
}

func (c *remoteDBServiceClient) ExecuteNoneQuery(ctx context.Context, in *DBRequest, opts ...grpc.CallOption) (*DBResponse, error) {
	out := new(DBResponse)
	err := c.cc.Invoke(ctx, "/proto.RemoteDBService/ExecuteNoneQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteDBServiceClient) ExecuteScalar(ctx context.Context, in *DBRequest, opts ...grpc.CallOption) (*DBResponse, error) {
	out := new(DBResponse)
	err := c.cc.Invoke(ctx, "/proto.RemoteDBService/ExecuteScalar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteDBServiceClient) ExecuteDataSet(ctx context.Context, in *DBRequest, opts ...grpc.CallOption) (*DBResponse, error) {
	out := new(DBResponse)
	err := c.cc.Invoke(ctx, "/proto.RemoteDBService/ExecuteDataSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteDBServiceServer is the server API for RemoteDBService service.
type RemoteDBServiceServer interface {
	ExecuteNoneQuery(context.Context, *DBRequest) (*DBResponse, error)
	ExecuteScalar(context.Context, *DBRequest) (*DBResponse, error)
	ExecuteDataSet(context.Context, *DBRequest) (*DBResponse, error)
}

func RegisterRemoteDBServiceServer(s *grpc.Server, srv RemoteDBServiceServer) {
	s.RegisterService(&_RemoteDBService_serviceDesc, srv)
}

func _RemoteDBService_ExecuteNoneQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDBServiceServer).ExecuteNoneQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RemoteDBService/ExecuteNoneQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDBServiceServer).ExecuteNoneQuery(ctx, req.(*DBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteDBService_ExecuteScalar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDBServiceServer).ExecuteScalar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RemoteDBService/ExecuteScalar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDBServiceServer).ExecuteScalar(ctx, req.(*DBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteDBService_ExecuteDataSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDBServiceServer).ExecuteDataSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RemoteDBService/ExecuteDataSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDBServiceServer).ExecuteDataSet(ctx, req.(*DBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteDBService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RemoteDBService",
	HandlerType: (*RemoteDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteNoneQuery",
			Handler:    _RemoteDBService_ExecuteNoneQuery_Handler,
		},
		{
			MethodName: "ExecuteScalar",
			Handler:    _RemoteDBService_ExecuteScalar_Handler,
		},
		{
			MethodName: "ExecuteDataSet",
			Handler:    _RemoteDBService_ExecuteDataSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dataRequest.proto",
}

func init() { proto.RegisterFile("dataRequest.proto", fileDescriptor_dataRequest_b3a812fe340b910b) }

var fileDescriptor_dataRequest_b3a812fe340b910b = []byte{
	// 678 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x4e, 0xdb, 0x4a,
	0x14, 0xbe, 0xc6, 0x24, 0x21, 0x27, 0xc0, 0x25, 0x23, 0x84, 0x2c, 0x74, 0x17, 0x91, 0x75, 0xdb,
	0x46, 0xaa, 0x14, 0x89, 0xa0, 0x52, 0x75, 0x9b, 0xc2, 0x02, 0xa9, 0xaa, 0xe8, 0x04, 0x75, 0xd5,
	0xcd, 0xc4, 0x3e, 0x81, 0x08, 0xc7, 0x63, 0x66, 0xc6, 0x04, 0xde, 0xa0, 0x2f, 0xd5, 0x5d, 0x17,
	0x55, 0x9f, 0xaa, 0x9a, 0x33, 0x63, 0xe3, 0xb4, 0x54, 0x62, 0x15, 0x7f, 0xe7, 0x3b, 0x3f, 0xdf,
	0xf9, 0x99, 0x40, 0x3f, 0x15, 0x46, 0x70, 0xbc, 0x2d, 0x51, 0x9b, 0x51, 0xa1, 0xa4, 0x91, 0xac,
	0x45, 0x3f, 0xf1, 0xf7, 0x00, 0xba, 0xa7, 0x13, 0x4f, 0xb1, 0x7d, 0x68, 0x19, 0x79, 0x83, 0x79,
	0x14, 0x0c, 0x82, 0x61, 0x97, 0x3b, 0xc0, 0x8e, 0x00, 0x34, 0xaa, 0x3b, 0x54, 0xe7, 0xf9, 0x5c,
	0x46, 0x1b, 0x83, 0x60, 0xd8, 0x1b, 0xf7, 0x5d, 0x9a, 0xd1, 0xb4, 0x26, 0x78, 0xc3, 0x89, 0x1d,
	0x40, 0x5b, 0x27, 0x6a, 0x51, 0x98, 0x28, 0xa4, 0x4c, 0x1e, 0xb1, 0x18, 0xb6, 0xf5, 0x6d, 0x36,
	0x35, 0xc2, 0xe0, 0x12, 0x73, 0x13, 0x6d, 0x12, 0xbb, 0x66, 0x63, 0x63, 0x80, 0x42, 0x28, 0xb1,
	0x44, 0x83, 0x4a, 0x47, 0xad, 0x41, 0x38, 0xec, 0x8d, 0x99, 0x2f, 0x77, 0x3a, 0xb9, 0xa8, 0x28,
	0xde, 0xf0, 0x8a, 0x6f, 0xa0, 0xd7, 0xa0, 0x18, 0x83, 0xcd, 0x5c, 0x2c, 0xd1, 0xb7, 0x41, 0xdf,
	0x56, 0x52, 0x3a, 0xbb, 0x7c, 0x28, 0x90, 0x3a, 0xe8, 0x72, 0x8f, 0xd8, 0x21, 0x6c, 0xa5, 0xb3,
	0x0f, 0x98, 0x5f, 0x99, 0x6b, 0x12, 0x1b, 0xf2, 0x1a, 0xdb, 0x79, 0xdc, 0x89, 0xac, 0x44, 0xaf,
	0xd3, 0x81, 0xf8, 0x6b, 0x00, 0x30, 0x5d, 0xef, 0x95, 0x90, 0x2f, 0xe7, 0x91, 0x15, 0x51, 0x48,
	0x65, 0xa8, 0x5c, 0x8b, 0xd3, 0x37, 0x15, 0x13, 0x46, 0xcc, 0x84, 0x46, 0x3f, 0x99, 0x1a, 0xdb,
	0x3c, 0xa5, 0x46, 0x75, 0x9e, 0xfa, 0x6a, 0x1e, 0xd9, 0x98, 0x42, 0x68, 0xbd, 0x92, 0x2a, 0x8d,
	0x5a, 0x2e, 0xa6, 0xc2, 0xf1, 0x8f, 0x00, 0xc0, 0xae, 0x4f, 0x17, 0x32, 0xd7, 0xc8, 0xfe, 0x83,
	0xae, 0x2e, 0x93, 0x04, 0x31, 0xc5, 0x94, 0xd4, 0x6c, 0xf1, 0x47, 0x03, 0x8b, 0xa0, 0xb3, 0x44,
	0xad, 0xc5, 0x55, 0x35, 0x82, 0x0a, 0xb2, 0x13, 0xe8, 0xe9, 0x44, 0x64, 0x42, 0x7d, 0xa6, 0x6e,
	0x43, 0x5a, 0xf1, 0x7e, 0x3d, 0xf3, 0xe9, 0x23, 0xc7, 0x9b, 0x8e, 0x6c, 0x00, 0x3d, 0x25, 0x57,
	0x67, 0xf3, 0x39, 0x26, 0x06, 0x9d, 0xee, 0x90, 0x37, 0x4d, 0x6c, 0x08, 0x1d, 0xdb, 0xa0, 0x46,
	0x43, 0xda, 0x7b, 0xe3, 0xdd, 0x2a, 0xab, 0x30, 0x62, 0x8a, 0x86, 0x57, 0x74, 0x7c, 0x0c, 0x1d,
	0x6f, 0x63, 0x43, 0x68, 0x1b, 0x31, 0xcb, 0x50, 0x47, 0x01, 0x6d, 0x7f, 0xaf, 0x11, 0x73, 0x69,
	0x09, 0xee, 0xf9, 0xb8, 0x80, 0x6e, 0x6d, 0x7c, 0x72, 0xeb, 0xaf, 0xa1, 0x93, 0xc8, 0xac, 0x5c,
	0xe6, 0x3a, 0xda, 0xa0, 0x5c, 0xfd, 0x46, 0xae, 0xf7, 0xc4, 0xf0, 0xca, 0x83, 0xc5, 0xb0, 0xa9,
	0xe4, 0x4a, 0x47, 0x21, 0x79, 0x36, 0x95, 0x72, 0xb9, 0xe2, 0xc4, 0xc5, 0x3f, 0xed, 0xc4, 0xeb,
	0x58, 0x7b, 0x21, 0x8b, 0x3c, 0xc5, 0x7b, 0x2a, 0xda, 0xe2, 0x0e, 0xd4, 0x4a, 0x36, 0x9e, 0xbc,
	0xbf, 0x70, 0xed, 0xfe, 0x0e, 0xa0, 0x9d, 0xb9, 0xeb, 0x73, 0xe3, 0xf3, 0xc8, 0xe6, 0x30, 0xd6,
	0xdb, 0xad, 0x9c, 0xbe, 0xed, 0x7e, 0x0b, 0x85, 0xc9, 0x42, 0x2f, 0x64, 0x1e, 0xb5, 0xc9, 0xfd,
	0xd1, 0x60, 0xb5, 0xd8, 0xe5, 0x60, 0xd4, 0x21, 0xc6, 0x01, 0x7b, 0x3e, 0x79, 0x99, 0x65, 0x76,
	0x42, 0xd1, 0x16, 0x9d, 0x44, 0x8d, 0xe3, 0x23, 0x37, 0x73, 0x2e, 0x57, 0xec, 0x25, 0xb4, 0xe9,
	0xba, 0xab, 0x99, 0xd7, 0xdd, 0x4f, 0xdc, 0xde, 0x3d, 0x1b, 0xbf, 0x81, 0x8e, 0x37, 0xfd, 0xa5,
	0xf7, 0xfa, 0xcd, 0xd8, 0xe6, 0xb7, 0xab, 0x37, 0xf3, 0x05, 0x76, 0xd6, 0xee, 0x88, 0xbd, 0xf0,
	0xed, 0x05, 0x6b, 0x7f, 0x27, 0x8d, 0xad, 0xb8, 0x8e, 0xff, 0x6f, 0x66, 0xfb, 0x53, 0x95, 0x23,
	0xc7, 0xdf, 0x02, 0xf8, 0x97, 0xe3, 0x52, 0x1a, 0x3c, 0x9d, 0xd8, 0x97, 0xb9, 0x48, 0x90, 0xbd,
	0x83, 0xbd, 0xb3, 0x7b, 0x4c, 0x4a, 0x83, 0x1f, 0x65, 0x8e, 0x9f, 0x4a, 0x54, 0x0f, 0xac, 0x3e,
	0xa4, 0xea, 0x1f, 0xef, 0xb0, 0xdf, 0xb0, 0xb8, 0x47, 0x14, 0xff, 0xc3, 0x4e, 0x60, 0xc7, 0x87,
	0x3a, 0xc5, 0xcf, 0x8d, 0x7b, 0x0b, 0xbb, 0x3e, 0xae, 0xba, 0xe4, 0xe7, 0x05, 0x4e, 0x5e, 0xc1,
	0xce, 0x7c, 0xa1, 0xaf, 0x47, 0x57, 0xaa, 0x48, 0x46, 0x2a, 0x15, 0x93, 0xfd, 0xdf, 0xba, 0xb9,
	0xb0, 0x31, 0x17, 0xc1, 0xac, 0x4d, 0xc1, 0xc7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x03,
	0x1d, 0x55, 0xd1, 0x05, 0x00, 0x00,
}
