// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dataRequest.proto

package remoteDataAccess

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DbRequest struct {
	// Token will be used to identify the server connection info
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Or the server connection info was given in the DbRequest
	ServerInfo *ServerInfo `protobuf:"bytes,2,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	// The script name to locate a DB script for execution
	Script string `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	// The plain text sql statement
	SqlStatement         string   `protobuf:"bytes,4,opt,name=sqlStatement,proto3" json:"sqlStatement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DbRequest) Reset()         { *m = DbRequest{} }
func (m *DbRequest) String() string { return proto.CompactTextString(m) }
func (*DbRequest) ProtoMessage()    {}
func (*DbRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{0}
}
func (m *DbRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbRequest.Unmarshal(m, b)
}
func (m *DbRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbRequest.Marshal(b, m, deterministic)
}
func (dst *DbRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbRequest.Merge(dst, src)
}
func (m *DbRequest) XXX_Size() int {
	return xxx_messageInfo_DbRequest.Size(m)
}
func (m *DbRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DbRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DbRequest proto.InternalMessageInfo

func (m *DbRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DbRequest) GetServerInfo() *ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

func (m *DbRequest) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *DbRequest) GetSqlStatement() string {
	if m != nil {
		return m.SqlStatement
	}
	return ""
}

type ServerInfo struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Database             string   `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{1}
}
func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (dst *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(dst, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *ServerInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerInfo) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ServerInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ServerInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type DbResponse struct {
	Succeeded            bool        `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ScalarValue          *DBAnyValue `protobuf:"bytes,3,opt,name=scalarValue,proto3" json:"scalarValue,omitempty"`
	RowEffected          int32       `protobuf:"varint,4,opt,name=rowEffected,proto3" json:"rowEffected,omitempty"`
	Dataset              *DataSet    `protobuf:"bytes,5,opt,name=dataset,proto3" json:"dataset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DbResponse) Reset()         { *m = DbResponse{} }
func (m *DbResponse) String() string { return proto.CompactTextString(m) }
func (*DbResponse) ProtoMessage()    {}
func (*DbResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{2}
}
func (m *DbResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbResponse.Unmarshal(m, b)
}
func (m *DbResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbResponse.Marshal(b, m, deterministic)
}
func (dst *DbResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbResponse.Merge(dst, src)
}
func (m *DbResponse) XXX_Size() int {
	return xxx_messageInfo_DbResponse.Size(m)
}
func (m *DbResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DbResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DbResponse proto.InternalMessageInfo

func (m *DbResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *DbResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DbResponse) GetScalarValue() *DBAnyValue {
	if m != nil {
		return m.ScalarValue
	}
	return nil
}

func (m *DbResponse) GetRowEffected() int32 {
	if m != nil {
		return m.RowEffected
	}
	return 0
}

func (m *DbResponse) GetDataset() *DataSet {
	if m != nil {
		return m.Dataset
	}
	return nil
}

type DataSet struct {
	Tables               []*DataTable `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DataSet) Reset()         { *m = DataSet{} }
func (m *DataSet) String() string { return proto.CompactTextString(m) }
func (*DataSet) ProtoMessage()    {}
func (*DataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{3}
}
func (m *DataSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSet.Unmarshal(m, b)
}
func (m *DataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSet.Marshal(b, m, deterministic)
}
func (dst *DataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSet.Merge(dst, src)
}
func (m *DataSet) XXX_Size() int {
	return xxx_messageInfo_DataSet.Size(m)
}
func (m *DataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSet.DiscardUnknown(m)
}

var xxx_messageInfo_DataSet proto.InternalMessageInfo

func (m *DataSet) GetTables() []*DataTable {
	if m != nil {
		return m.Tables
	}
	return nil
}

type DataTable struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Column definitions of this table
	Columns []*DataColumn `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Rows in this table
	Rows                 []*DataRow `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataTable) Reset()         { *m = DataTable{} }
func (m *DataTable) String() string { return proto.CompactTextString(m) }
func (*DataTable) ProtoMessage()    {}
func (*DataTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{4}
}
func (m *DataTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTable.Unmarshal(m, b)
}
func (m *DataTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTable.Marshal(b, m, deterministic)
}
func (dst *DataTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTable.Merge(dst, src)
}
func (m *DataTable) XXX_Size() int {
	return xxx_messageInfo_DataTable.Size(m)
}
func (m *DataTable) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTable.DiscardUnknown(m)
}

var xxx_messageInfo_DataTable proto.InternalMessageInfo

func (m *DataTable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataTable) GetColumns() []*DataColumn {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *DataTable) GetRows() []*DataRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type DataColumn struct {
	// The name of the column
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The db type of the column
	DbType string `protobuf:"bytes,3,opt,name=dbType,proto3" json:"dbType,omitempty"`
	// The db size
	DbSize               int32    `protobuf:"varint,4,opt,name=dbSize,proto3" json:"dbSize,omitempty"`
	Precision            int32    `protobuf:"varint,5,opt,name=precision,proto3" json:"precision,omitempty"`
	Index                int32    `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataColumn) Reset()         { *m = DataColumn{} }
func (m *DataColumn) String() string { return proto.CompactTextString(m) }
func (*DataColumn) ProtoMessage()    {}
func (*DataColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{5}
}
func (m *DataColumn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataColumn.Unmarshal(m, b)
}
func (m *DataColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataColumn.Marshal(b, m, deterministic)
}
func (dst *DataColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataColumn.Merge(dst, src)
}
func (m *DataColumn) XXX_Size() int {
	return xxx_messageInfo_DataColumn.Size(m)
}
func (m *DataColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_DataColumn.DiscardUnknown(m)
}

var xxx_messageInfo_DataColumn proto.InternalMessageInfo

func (m *DataColumn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataColumn) GetDbType() string {
	if m != nil {
		return m.DbType
	}
	return ""
}

func (m *DataColumn) GetDbSize() int32 {
	if m != nil {
		return m.DbSize
	}
	return 0
}

func (m *DataColumn) GetPrecision() int32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *DataColumn) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type DataRow struct {
	Sfixed32Collection   *DBSignedFixed32Collection `protobuf:"bytes,1,opt,name=sfixed32Collection,proto3" json:"sfixed32Collection,omitempty"`
	Sfixed64Collection   *DBSignedFixed64Collection `protobuf:"bytes,2,opt,name=sfixed64Collection,proto3" json:"sfixed64Collection,omitempty"`
	BooleanCollection    *DBBooleanCollection       `protobuf:"bytes,3,opt,name=booleanCollection,proto3" json:"booleanCollection,omitempty"`
	StringCollection     *DBStringCollection        `protobuf:"bytes,4,opt,name=stringCollection,proto3" json:"stringCollection,omitempty"`
	Sint32Collection     *DBSInt32Collection        `protobuf:"bytes,5,opt,name=sint32Collection,proto3" json:"sint32Collection,omitempty"`
	Sint64Collection     *DBSInt64Collection        `protobuf:"bytes,6,opt,name=sint64Collection,proto3" json:"sint64Collection,omitempty"`
	Uint32Collection     *DBUInt32Collection        `protobuf:"bytes,7,opt,name=uint32Collection,proto3" json:"uint32Collection,omitempty"`
	Uint64Collection     *DBUInt64Collection        `protobuf:"bytes,8,opt,name=uint64Collection,proto3" json:"uint64Collection,omitempty"`
	Int32Collection      *DBInt32Collection         `protobuf:"bytes,9,opt,name=int32Collection,proto3" json:"int32Collection,omitempty"`
	Int64Collection      *DBInt64Collection         `protobuf:"bytes,10,opt,name=int64Collection,proto3" json:"int64Collection,omitempty"`
	BytesCollection      *DBBytesCollection         `protobuf:"bytes,11,opt,name=bytesCollection,proto3" json:"bytesCollection,omitempty"`
	FloatCollection      *DBFloatCollection         `protobuf:"bytes,12,opt,name=floatCollection,proto3" json:"floatCollection,omitempty"`
	DoubleCollection     *DBDoubleCollection        `protobuf:"bytes,13,opt,name=doubleCollection,proto3" json:"doubleCollection,omitempty"`
	AnyCollection        *DBAnyCollection           `protobuf:"bytes,14,opt,name=anyCollection,proto3" json:"anyCollection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DataRow) Reset()         { *m = DataRow{} }
func (m *DataRow) String() string { return proto.CompactTextString(m) }
func (*DataRow) ProtoMessage()    {}
func (*DataRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{6}
}
func (m *DataRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRow.Unmarshal(m, b)
}
func (m *DataRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRow.Marshal(b, m, deterministic)
}
func (dst *DataRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRow.Merge(dst, src)
}
func (m *DataRow) XXX_Size() int {
	return xxx_messageInfo_DataRow.Size(m)
}
func (m *DataRow) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRow.DiscardUnknown(m)
}

var xxx_messageInfo_DataRow proto.InternalMessageInfo

func (m *DataRow) GetSfixed32Collection() *DBSignedFixed32Collection {
	if m != nil {
		return m.Sfixed32Collection
	}
	return nil
}

func (m *DataRow) GetSfixed64Collection() *DBSignedFixed64Collection {
	if m != nil {
		return m.Sfixed64Collection
	}
	return nil
}

func (m *DataRow) GetBooleanCollection() *DBBooleanCollection {
	if m != nil {
		return m.BooleanCollection
	}
	return nil
}

func (m *DataRow) GetStringCollection() *DBStringCollection {
	if m != nil {
		return m.StringCollection
	}
	return nil
}

func (m *DataRow) GetSint32Collection() *DBSInt32Collection {
	if m != nil {
		return m.Sint32Collection
	}
	return nil
}

func (m *DataRow) GetSint64Collection() *DBSInt64Collection {
	if m != nil {
		return m.Sint64Collection
	}
	return nil
}

func (m *DataRow) GetUint32Collection() *DBUInt32Collection {
	if m != nil {
		return m.Uint32Collection
	}
	return nil
}

func (m *DataRow) GetUint64Collection() *DBUInt64Collection {
	if m != nil {
		return m.Uint64Collection
	}
	return nil
}

func (m *DataRow) GetInt32Collection() *DBInt32Collection {
	if m != nil {
		return m.Int32Collection
	}
	return nil
}

func (m *DataRow) GetInt64Collection() *DBInt64Collection {
	if m != nil {
		return m.Int64Collection
	}
	return nil
}

func (m *DataRow) GetBytesCollection() *DBBytesCollection {
	if m != nil {
		return m.BytesCollection
	}
	return nil
}

func (m *DataRow) GetFloatCollection() *DBFloatCollection {
	if m != nil {
		return m.FloatCollection
	}
	return nil
}

func (m *DataRow) GetDoubleCollection() *DBDoubleCollection {
	if m != nil {
		return m.DoubleCollection
	}
	return nil
}

func (m *DataRow) GetAnyCollection() *DBAnyCollection {
	if m != nil {
		return m.AnyCollection
	}
	return nil
}

type DBAnyCollection struct {
	Values               []*DBAnyValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DBAnyCollection) Reset()         { *m = DBAnyCollection{} }
func (m *DBAnyCollection) String() string { return proto.CompactTextString(m) }
func (*DBAnyCollection) ProtoMessage()    {}
func (*DBAnyCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{7}
}
func (m *DBAnyCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBAnyCollection.Unmarshal(m, b)
}
func (m *DBAnyCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBAnyCollection.Marshal(b, m, deterministic)
}
func (dst *DBAnyCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBAnyCollection.Merge(dst, src)
}
func (m *DBAnyCollection) XXX_Size() int {
	return xxx_messageInfo_DBAnyCollection.Size(m)
}
func (m *DBAnyCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBAnyCollection.DiscardUnknown(m)
}

var xxx_messageInfo_DBAnyCollection proto.InternalMessageInfo

func (m *DBAnyCollection) GetValues() []*DBAnyValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBAnyValue struct {
	ValueType            string   `protobuf:"bytes,1,opt,name=valueType,proto3" json:"valueType,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBAnyValue) Reset()         { *m = DBAnyValue{} }
func (m *DBAnyValue) String() string { return proto.CompactTextString(m) }
func (*DBAnyValue) ProtoMessage()    {}
func (*DBAnyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{8}
}
func (m *DBAnyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBAnyValue.Unmarshal(m, b)
}
func (m *DBAnyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBAnyValue.Marshal(b, m, deterministic)
}
func (dst *DBAnyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBAnyValue.Merge(dst, src)
}
func (m *DBAnyValue) XXX_Size() int {
	return xxx_messageInfo_DBAnyValue.Size(m)
}
func (m *DBAnyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DBAnyValue.DiscardUnknown(m)
}

var xxx_messageInfo_DBAnyValue proto.InternalMessageInfo

func (m *DBAnyValue) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

func (m *DBAnyValue) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type DBInt32Collection struct {
	Values               []*DBInt32Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DBInt32Collection) Reset()         { *m = DBInt32Collection{} }
func (m *DBInt32Collection) String() string { return proto.CompactTextString(m) }
func (*DBInt32Collection) ProtoMessage()    {}
func (*DBInt32Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{9}
}
func (m *DBInt32Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBInt32Collection.Unmarshal(m, b)
}
func (m *DBInt32Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBInt32Collection.Marshal(b, m, deterministic)
}
func (dst *DBInt32Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBInt32Collection.Merge(dst, src)
}
func (m *DBInt32Collection) XXX_Size() int {
	return xxx_messageInfo_DBInt32Collection.Size(m)
}
func (m *DBInt32Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBInt32Collection.DiscardUnknown(m)
}

var xxx_messageInfo_DBInt32Collection proto.InternalMessageInfo

func (m *DBInt32Collection) GetValues() []*DBInt32Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBInt32Value struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBInt32Value) Reset()         { *m = DBInt32Value{} }
func (m *DBInt32Value) String() string { return proto.CompactTextString(m) }
func (*DBInt32Value) ProtoMessage()    {}
func (*DBInt32Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{10}
}
func (m *DBInt32Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBInt32Value.Unmarshal(m, b)
}
func (m *DBInt32Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBInt32Value.Marshal(b, m, deterministic)
}
func (dst *DBInt32Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBInt32Value.Merge(dst, src)
}
func (m *DBInt32Value) XXX_Size() int {
	return xxx_messageInfo_DBInt32Value.Size(m)
}
func (m *DBInt32Value) XXX_DiscardUnknown() {
	xxx_messageInfo_DBInt32Value.DiscardUnknown(m)
}

var xxx_messageInfo_DBInt32Value proto.InternalMessageInfo

func (m *DBInt32Value) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBInt32Value) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBInt64Collection struct {
	Values               []*DBInt64Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DBInt64Collection) Reset()         { *m = DBInt64Collection{} }
func (m *DBInt64Collection) String() string { return proto.CompactTextString(m) }
func (*DBInt64Collection) ProtoMessage()    {}
func (*DBInt64Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{11}
}
func (m *DBInt64Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBInt64Collection.Unmarshal(m, b)
}
func (m *DBInt64Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBInt64Collection.Marshal(b, m, deterministic)
}
func (dst *DBInt64Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBInt64Collection.Merge(dst, src)
}
func (m *DBInt64Collection) XXX_Size() int {
	return xxx_messageInfo_DBInt64Collection.Size(m)
}
func (m *DBInt64Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBInt64Collection.DiscardUnknown(m)
}

var xxx_messageInfo_DBInt64Collection proto.InternalMessageInfo

func (m *DBInt64Collection) GetValues() []*DBInt64Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBInt64Value struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBInt64Value) Reset()         { *m = DBInt64Value{} }
func (m *DBInt64Value) String() string { return proto.CompactTextString(m) }
func (*DBInt64Value) ProtoMessage()    {}
func (*DBInt64Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{12}
}
func (m *DBInt64Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBInt64Value.Unmarshal(m, b)
}
func (m *DBInt64Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBInt64Value.Marshal(b, m, deterministic)
}
func (dst *DBInt64Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBInt64Value.Merge(dst, src)
}
func (m *DBInt64Value) XXX_Size() int {
	return xxx_messageInfo_DBInt64Value.Size(m)
}
func (m *DBInt64Value) XXX_DiscardUnknown() {
	xxx_messageInfo_DBInt64Value.DiscardUnknown(m)
}

var xxx_messageInfo_DBInt64Value proto.InternalMessageInfo

func (m *DBInt64Value) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBInt64Value) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBSInt32Collection struct {
	Values               []*DBSInt32Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DBSInt32Collection) Reset()         { *m = DBSInt32Collection{} }
func (m *DBSInt32Collection) String() string { return proto.CompactTextString(m) }
func (*DBSInt32Collection) ProtoMessage()    {}
func (*DBSInt32Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{13}
}
func (m *DBSInt32Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSInt32Collection.Unmarshal(m, b)
}
func (m *DBSInt32Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSInt32Collection.Marshal(b, m, deterministic)
}
func (dst *DBSInt32Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSInt32Collection.Merge(dst, src)
}
func (m *DBSInt32Collection) XXX_Size() int {
	return xxx_messageInfo_DBSInt32Collection.Size(m)
}
func (m *DBSInt32Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSInt32Collection.DiscardUnknown(m)
}

var xxx_messageInfo_DBSInt32Collection proto.InternalMessageInfo

func (m *DBSInt32Collection) GetValues() []*DBSInt32Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBSInt32Value struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                int32    `protobuf:"zigzag32,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBSInt32Value) Reset()         { *m = DBSInt32Value{} }
func (m *DBSInt32Value) String() string { return proto.CompactTextString(m) }
func (*DBSInt32Value) ProtoMessage()    {}
func (*DBSInt32Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{14}
}
func (m *DBSInt32Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSInt32Value.Unmarshal(m, b)
}
func (m *DBSInt32Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSInt32Value.Marshal(b, m, deterministic)
}
func (dst *DBSInt32Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSInt32Value.Merge(dst, src)
}
func (m *DBSInt32Value) XXX_Size() int {
	return xxx_messageInfo_DBSInt32Value.Size(m)
}
func (m *DBSInt32Value) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSInt32Value.DiscardUnknown(m)
}

var xxx_messageInfo_DBSInt32Value proto.InternalMessageInfo

func (m *DBSInt32Value) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBSInt32Value) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBSInt64Collection struct {
	Values               []*DBSInt64Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DBSInt64Collection) Reset()         { *m = DBSInt64Collection{} }
func (m *DBSInt64Collection) String() string { return proto.CompactTextString(m) }
func (*DBSInt64Collection) ProtoMessage()    {}
func (*DBSInt64Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{15}
}
func (m *DBSInt64Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSInt64Collection.Unmarshal(m, b)
}
func (m *DBSInt64Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSInt64Collection.Marshal(b, m, deterministic)
}
func (dst *DBSInt64Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSInt64Collection.Merge(dst, src)
}
func (m *DBSInt64Collection) XXX_Size() int {
	return xxx_messageInfo_DBSInt64Collection.Size(m)
}
func (m *DBSInt64Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSInt64Collection.DiscardUnknown(m)
}

var xxx_messageInfo_DBSInt64Collection proto.InternalMessageInfo

func (m *DBSInt64Collection) GetValues() []*DBSInt64Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBSInt64Value struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                int64    `protobuf:"zigzag64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBSInt64Value) Reset()         { *m = DBSInt64Value{} }
func (m *DBSInt64Value) String() string { return proto.CompactTextString(m) }
func (*DBSInt64Value) ProtoMessage()    {}
func (*DBSInt64Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{16}
}
func (m *DBSInt64Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSInt64Value.Unmarshal(m, b)
}
func (m *DBSInt64Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSInt64Value.Marshal(b, m, deterministic)
}
func (dst *DBSInt64Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSInt64Value.Merge(dst, src)
}
func (m *DBSInt64Value) XXX_Size() int {
	return xxx_messageInfo_DBSInt64Value.Size(m)
}
func (m *DBSInt64Value) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSInt64Value.DiscardUnknown(m)
}

var xxx_messageInfo_DBSInt64Value proto.InternalMessageInfo

func (m *DBSInt64Value) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBSInt64Value) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBUInt32Collection struct {
	Values               []*DBUInt32Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DBUInt32Collection) Reset()         { *m = DBUInt32Collection{} }
func (m *DBUInt32Collection) String() string { return proto.CompactTextString(m) }
func (*DBUInt32Collection) ProtoMessage()    {}
func (*DBUInt32Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{17}
}
func (m *DBUInt32Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUInt32Collection.Unmarshal(m, b)
}
func (m *DBUInt32Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUInt32Collection.Marshal(b, m, deterministic)
}
func (dst *DBUInt32Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUInt32Collection.Merge(dst, src)
}
func (m *DBUInt32Collection) XXX_Size() int {
	return xxx_messageInfo_DBUInt32Collection.Size(m)
}
func (m *DBUInt32Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUInt32Collection.DiscardUnknown(m)
}

var xxx_messageInfo_DBUInt32Collection proto.InternalMessageInfo

func (m *DBUInt32Collection) GetValues() []*DBUInt32Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBUInt32Value struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                uint32   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUInt32Value) Reset()         { *m = DBUInt32Value{} }
func (m *DBUInt32Value) String() string { return proto.CompactTextString(m) }
func (*DBUInt32Value) ProtoMessage()    {}
func (*DBUInt32Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{18}
}
func (m *DBUInt32Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUInt32Value.Unmarshal(m, b)
}
func (m *DBUInt32Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUInt32Value.Marshal(b, m, deterministic)
}
func (dst *DBUInt32Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUInt32Value.Merge(dst, src)
}
func (m *DBUInt32Value) XXX_Size() int {
	return xxx_messageInfo_DBUInt32Value.Size(m)
}
func (m *DBUInt32Value) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUInt32Value.DiscardUnknown(m)
}

var xxx_messageInfo_DBUInt32Value proto.InternalMessageInfo

func (m *DBUInt32Value) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBUInt32Value) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBUInt64Collection struct {
	Values               []*DBUInt64Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DBUInt64Collection) Reset()         { *m = DBUInt64Collection{} }
func (m *DBUInt64Collection) String() string { return proto.CompactTextString(m) }
func (*DBUInt64Collection) ProtoMessage()    {}
func (*DBUInt64Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{19}
}
func (m *DBUInt64Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUInt64Collection.Unmarshal(m, b)
}
func (m *DBUInt64Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUInt64Collection.Marshal(b, m, deterministic)
}
func (dst *DBUInt64Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUInt64Collection.Merge(dst, src)
}
func (m *DBUInt64Collection) XXX_Size() int {
	return xxx_messageInfo_DBUInt64Collection.Size(m)
}
func (m *DBUInt64Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUInt64Collection.DiscardUnknown(m)
}

var xxx_messageInfo_DBUInt64Collection proto.InternalMessageInfo

func (m *DBUInt64Collection) GetValues() []*DBUInt64Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBUInt64Value struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                uint64   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBUInt64Value) Reset()         { *m = DBUInt64Value{} }
func (m *DBUInt64Value) String() string { return proto.CompactTextString(m) }
func (*DBUInt64Value) ProtoMessage()    {}
func (*DBUInt64Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{20}
}
func (m *DBUInt64Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBUInt64Value.Unmarshal(m, b)
}
func (m *DBUInt64Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBUInt64Value.Marshal(b, m, deterministic)
}
func (dst *DBUInt64Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBUInt64Value.Merge(dst, src)
}
func (m *DBUInt64Value) XXX_Size() int {
	return xxx_messageInfo_DBUInt64Value.Size(m)
}
func (m *DBUInt64Value) XXX_DiscardUnknown() {
	xxx_messageInfo_DBUInt64Value.DiscardUnknown(m)
}

var xxx_messageInfo_DBUInt64Value proto.InternalMessageInfo

func (m *DBUInt64Value) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBUInt64Value) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBSignedFixed32Collection struct {
	Values               []*DBSignedFixed32Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DBSignedFixed32Collection) Reset()         { *m = DBSignedFixed32Collection{} }
func (m *DBSignedFixed32Collection) String() string { return proto.CompactTextString(m) }
func (*DBSignedFixed32Collection) ProtoMessage()    {}
func (*DBSignedFixed32Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{21}
}
func (m *DBSignedFixed32Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSignedFixed32Collection.Unmarshal(m, b)
}
func (m *DBSignedFixed32Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSignedFixed32Collection.Marshal(b, m, deterministic)
}
func (dst *DBSignedFixed32Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSignedFixed32Collection.Merge(dst, src)
}
func (m *DBSignedFixed32Collection) XXX_Size() int {
	return xxx_messageInfo_DBSignedFixed32Collection.Size(m)
}
func (m *DBSignedFixed32Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSignedFixed32Collection.DiscardUnknown(m)
}

var xxx_messageInfo_DBSignedFixed32Collection proto.InternalMessageInfo

func (m *DBSignedFixed32Collection) GetValues() []*DBSignedFixed32Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBSignedFixed32Value struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                int32    `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBSignedFixed32Value) Reset()         { *m = DBSignedFixed32Value{} }
func (m *DBSignedFixed32Value) String() string { return proto.CompactTextString(m) }
func (*DBSignedFixed32Value) ProtoMessage()    {}
func (*DBSignedFixed32Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{22}
}
func (m *DBSignedFixed32Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSignedFixed32Value.Unmarshal(m, b)
}
func (m *DBSignedFixed32Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSignedFixed32Value.Marshal(b, m, deterministic)
}
func (dst *DBSignedFixed32Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSignedFixed32Value.Merge(dst, src)
}
func (m *DBSignedFixed32Value) XXX_Size() int {
	return xxx_messageInfo_DBSignedFixed32Value.Size(m)
}
func (m *DBSignedFixed32Value) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSignedFixed32Value.DiscardUnknown(m)
}

var xxx_messageInfo_DBSignedFixed32Value proto.InternalMessageInfo

func (m *DBSignedFixed32Value) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBSignedFixed32Value) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBSignedFixed64Collection struct {
	Values               []*DBSignedFixed64Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DBSignedFixed64Collection) Reset()         { *m = DBSignedFixed64Collection{} }
func (m *DBSignedFixed64Collection) String() string { return proto.CompactTextString(m) }
func (*DBSignedFixed64Collection) ProtoMessage()    {}
func (*DBSignedFixed64Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{23}
}
func (m *DBSignedFixed64Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSignedFixed64Collection.Unmarshal(m, b)
}
func (m *DBSignedFixed64Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSignedFixed64Collection.Marshal(b, m, deterministic)
}
func (dst *DBSignedFixed64Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSignedFixed64Collection.Merge(dst, src)
}
func (m *DBSignedFixed64Collection) XXX_Size() int {
	return xxx_messageInfo_DBSignedFixed64Collection.Size(m)
}
func (m *DBSignedFixed64Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSignedFixed64Collection.DiscardUnknown(m)
}

var xxx_messageInfo_DBSignedFixed64Collection proto.InternalMessageInfo

func (m *DBSignedFixed64Collection) GetValues() []*DBSignedFixed64Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBSignedFixed64Value struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                int64    `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBSignedFixed64Value) Reset()         { *m = DBSignedFixed64Value{} }
func (m *DBSignedFixed64Value) String() string { return proto.CompactTextString(m) }
func (*DBSignedFixed64Value) ProtoMessage()    {}
func (*DBSignedFixed64Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{24}
}
func (m *DBSignedFixed64Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBSignedFixed64Value.Unmarshal(m, b)
}
func (m *DBSignedFixed64Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBSignedFixed64Value.Marshal(b, m, deterministic)
}
func (dst *DBSignedFixed64Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBSignedFixed64Value.Merge(dst, src)
}
func (m *DBSignedFixed64Value) XXX_Size() int {
	return xxx_messageInfo_DBSignedFixed64Value.Size(m)
}
func (m *DBSignedFixed64Value) XXX_DiscardUnknown() {
	xxx_messageInfo_DBSignedFixed64Value.DiscardUnknown(m)
}

var xxx_messageInfo_DBSignedFixed64Value proto.InternalMessageInfo

func (m *DBSignedFixed64Value) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBSignedFixed64Value) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBBooleanCollection struct {
	Values               []*DBBooleanValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DBBooleanCollection) Reset()         { *m = DBBooleanCollection{} }
func (m *DBBooleanCollection) String() string { return proto.CompactTextString(m) }
func (*DBBooleanCollection) ProtoMessage()    {}
func (*DBBooleanCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{25}
}
func (m *DBBooleanCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBBooleanCollection.Unmarshal(m, b)
}
func (m *DBBooleanCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBBooleanCollection.Marshal(b, m, deterministic)
}
func (dst *DBBooleanCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBBooleanCollection.Merge(dst, src)
}
func (m *DBBooleanCollection) XXX_Size() int {
	return xxx_messageInfo_DBBooleanCollection.Size(m)
}
func (m *DBBooleanCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBBooleanCollection.DiscardUnknown(m)
}

var xxx_messageInfo_DBBooleanCollection proto.InternalMessageInfo

func (m *DBBooleanCollection) GetValues() []*DBBooleanValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBBooleanValue struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                bool     `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBBooleanValue) Reset()         { *m = DBBooleanValue{} }
func (m *DBBooleanValue) String() string { return proto.CompactTextString(m) }
func (*DBBooleanValue) ProtoMessage()    {}
func (*DBBooleanValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{26}
}
func (m *DBBooleanValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBBooleanValue.Unmarshal(m, b)
}
func (m *DBBooleanValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBBooleanValue.Marshal(b, m, deterministic)
}
func (dst *DBBooleanValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBBooleanValue.Merge(dst, src)
}
func (m *DBBooleanValue) XXX_Size() int {
	return xxx_messageInfo_DBBooleanValue.Size(m)
}
func (m *DBBooleanValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DBBooleanValue.DiscardUnknown(m)
}

var xxx_messageInfo_DBBooleanValue proto.InternalMessageInfo

func (m *DBBooleanValue) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBBooleanValue) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type DBStringCollection struct {
	Values               []*DBStringValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DBStringCollection) Reset()         { *m = DBStringCollection{} }
func (m *DBStringCollection) String() string { return proto.CompactTextString(m) }
func (*DBStringCollection) ProtoMessage()    {}
func (*DBStringCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{27}
}
func (m *DBStringCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBStringCollection.Unmarshal(m, b)
}
func (m *DBStringCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBStringCollection.Marshal(b, m, deterministic)
}
func (dst *DBStringCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBStringCollection.Merge(dst, src)
}
func (m *DBStringCollection) XXX_Size() int {
	return xxx_messageInfo_DBStringCollection.Size(m)
}
func (m *DBStringCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBStringCollection.DiscardUnknown(m)
}

var xxx_messageInfo_DBStringCollection proto.InternalMessageInfo

func (m *DBStringCollection) GetValues() []*DBStringValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBStringValue struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBStringValue) Reset()         { *m = DBStringValue{} }
func (m *DBStringValue) String() string { return proto.CompactTextString(m) }
func (*DBStringValue) ProtoMessage()    {}
func (*DBStringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{28}
}
func (m *DBStringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBStringValue.Unmarshal(m, b)
}
func (m *DBStringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBStringValue.Marshal(b, m, deterministic)
}
func (dst *DBStringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBStringValue.Merge(dst, src)
}
func (m *DBStringValue) XXX_Size() int {
	return xxx_messageInfo_DBStringValue.Size(m)
}
func (m *DBStringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DBStringValue.DiscardUnknown(m)
}

var xxx_messageInfo_DBStringValue proto.InternalMessageInfo

func (m *DBStringValue) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBStringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DBBytesCollection struct {
	Values               []*DBBytesValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DBBytesCollection) Reset()         { *m = DBBytesCollection{} }
func (m *DBBytesCollection) String() string { return proto.CompactTextString(m) }
func (*DBBytesCollection) ProtoMessage()    {}
func (*DBBytesCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{29}
}
func (m *DBBytesCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBBytesCollection.Unmarshal(m, b)
}
func (m *DBBytesCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBBytesCollection.Marshal(b, m, deterministic)
}
func (dst *DBBytesCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBBytesCollection.Merge(dst, src)
}
func (m *DBBytesCollection) XXX_Size() int {
	return xxx_messageInfo_DBBytesCollection.Size(m)
}
func (m *DBBytesCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBBytesCollection.DiscardUnknown(m)
}

var xxx_messageInfo_DBBytesCollection proto.InternalMessageInfo

func (m *DBBytesCollection) GetValues() []*DBBytesValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBBytesValue struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBBytesValue) Reset()         { *m = DBBytesValue{} }
func (m *DBBytesValue) String() string { return proto.CompactTextString(m) }
func (*DBBytesValue) ProtoMessage()    {}
func (*DBBytesValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{30}
}
func (m *DBBytesValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBBytesValue.Unmarshal(m, b)
}
func (m *DBBytesValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBBytesValue.Marshal(b, m, deterministic)
}
func (dst *DBBytesValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBBytesValue.Merge(dst, src)
}
func (m *DBBytesValue) XXX_Size() int {
	return xxx_messageInfo_DBBytesValue.Size(m)
}
func (m *DBBytesValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DBBytesValue.DiscardUnknown(m)
}

var xxx_messageInfo_DBBytesValue proto.InternalMessageInfo

func (m *DBBytesValue) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBBytesValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DBDateTimeCollection struct {
	Values               []*DBDateTimeValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DBDateTimeCollection) Reset()         { *m = DBDateTimeCollection{} }
func (m *DBDateTimeCollection) String() string { return proto.CompactTextString(m) }
func (*DBDateTimeCollection) ProtoMessage()    {}
func (*DBDateTimeCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{31}
}
func (m *DBDateTimeCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBDateTimeCollection.Unmarshal(m, b)
}
func (m *DBDateTimeCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBDateTimeCollection.Marshal(b, m, deterministic)
}
func (dst *DBDateTimeCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBDateTimeCollection.Merge(dst, src)
}
func (m *DBDateTimeCollection) XXX_Size() int {
	return xxx_messageInfo_DBDateTimeCollection.Size(m)
}
func (m *DBDateTimeCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBDateTimeCollection.DiscardUnknown(m)
}

var xxx_messageInfo_DBDateTimeCollection proto.InternalMessageInfo

func (m *DBDateTimeCollection) GetValues() []*DBDateTimeValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBDateTimeValue struct {
	Index                int32                `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DBDateTimeValue) Reset()         { *m = DBDateTimeValue{} }
func (m *DBDateTimeValue) String() string { return proto.CompactTextString(m) }
func (*DBDateTimeValue) ProtoMessage()    {}
func (*DBDateTimeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{32}
}
func (m *DBDateTimeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBDateTimeValue.Unmarshal(m, b)
}
func (m *DBDateTimeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBDateTimeValue.Marshal(b, m, deterministic)
}
func (dst *DBDateTimeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBDateTimeValue.Merge(dst, src)
}
func (m *DBDateTimeValue) XXX_Size() int {
	return xxx_messageInfo_DBDateTimeValue.Size(m)
}
func (m *DBDateTimeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DBDateTimeValue.DiscardUnknown(m)
}

var xxx_messageInfo_DBDateTimeValue proto.InternalMessageInfo

func (m *DBDateTimeValue) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBDateTimeValue) GetValue() *timestamp.Timestamp {
	if m != nil {
		return m.Value
	}
	return nil
}

type DBFloatCollection struct {
	Values               []*DBFloatValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DBFloatCollection) Reset()         { *m = DBFloatCollection{} }
func (m *DBFloatCollection) String() string { return proto.CompactTextString(m) }
func (*DBFloatCollection) ProtoMessage()    {}
func (*DBFloatCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{33}
}
func (m *DBFloatCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBFloatCollection.Unmarshal(m, b)
}
func (m *DBFloatCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBFloatCollection.Marshal(b, m, deterministic)
}
func (dst *DBFloatCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBFloatCollection.Merge(dst, src)
}
func (m *DBFloatCollection) XXX_Size() int {
	return xxx_messageInfo_DBFloatCollection.Size(m)
}
func (m *DBFloatCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBFloatCollection.DiscardUnknown(m)
}

var xxx_messageInfo_DBFloatCollection proto.InternalMessageInfo

func (m *DBFloatCollection) GetValues() []*DBFloatValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBFloatValue struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                float32  `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBFloatValue) Reset()         { *m = DBFloatValue{} }
func (m *DBFloatValue) String() string { return proto.CompactTextString(m) }
func (*DBFloatValue) ProtoMessage()    {}
func (*DBFloatValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{34}
}
func (m *DBFloatValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBFloatValue.Unmarshal(m, b)
}
func (m *DBFloatValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBFloatValue.Marshal(b, m, deterministic)
}
func (dst *DBFloatValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBFloatValue.Merge(dst, src)
}
func (m *DBFloatValue) XXX_Size() int {
	return xxx_messageInfo_DBFloatValue.Size(m)
}
func (m *DBFloatValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DBFloatValue.DiscardUnknown(m)
}

var xxx_messageInfo_DBFloatValue proto.InternalMessageInfo

func (m *DBFloatValue) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBFloatValue) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DBDoubleCollection struct {
	Values               []*DBDoubleValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DBDoubleCollection) Reset()         { *m = DBDoubleCollection{} }
func (m *DBDoubleCollection) String() string { return proto.CompactTextString(m) }
func (*DBDoubleCollection) ProtoMessage()    {}
func (*DBDoubleCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{35}
}
func (m *DBDoubleCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBDoubleCollection.Unmarshal(m, b)
}
func (m *DBDoubleCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBDoubleCollection.Marshal(b, m, deterministic)
}
func (dst *DBDoubleCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBDoubleCollection.Merge(dst, src)
}
func (m *DBDoubleCollection) XXX_Size() int {
	return xxx_messageInfo_DBDoubleCollection.Size(m)
}
func (m *DBDoubleCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_DBDoubleCollection.DiscardUnknown(m)
}

var xxx_messageInfo_DBDoubleCollection proto.InternalMessageInfo

func (m *DBDoubleCollection) GetValues() []*DBDoubleValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type DBDoubleValue struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBDoubleValue) Reset()         { *m = DBDoubleValue{} }
func (m *DBDoubleValue) String() string { return proto.CompactTextString(m) }
func (*DBDoubleValue) ProtoMessage()    {}
func (*DBDoubleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataRequest_b9e3e327626b2af9, []int{36}
}
func (m *DBDoubleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBDoubleValue.Unmarshal(m, b)
}
func (m *DBDoubleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBDoubleValue.Marshal(b, m, deterministic)
}
func (dst *DBDoubleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBDoubleValue.Merge(dst, src)
}
func (m *DBDoubleValue) XXX_Size() int {
	return xxx_messageInfo_DBDoubleValue.Size(m)
}
func (m *DBDoubleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DBDoubleValue.DiscardUnknown(m)
}

var xxx_messageInfo_DBDoubleValue proto.InternalMessageInfo

func (m *DBDoubleValue) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DBDoubleValue) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*DbRequest)(nil), "remoteDataAccess.DbRequest")
	proto.RegisterType((*ServerInfo)(nil), "remoteDataAccess.ServerInfo")
	proto.RegisterType((*DbResponse)(nil), "remoteDataAccess.DbResponse")
	proto.RegisterType((*DataSet)(nil), "remoteDataAccess.DataSet")
	proto.RegisterType((*DataTable)(nil), "remoteDataAccess.DataTable")
	proto.RegisterType((*DataColumn)(nil), "remoteDataAccess.DataColumn")
	proto.RegisterType((*DataRow)(nil), "remoteDataAccess.DataRow")
	proto.RegisterType((*DBAnyCollection)(nil), "remoteDataAccess.DBAnyCollection")
	proto.RegisterType((*DBAnyValue)(nil), "remoteDataAccess.DBAnyValue")
	proto.RegisterType((*DBInt32Collection)(nil), "remoteDataAccess.DBInt32Collection")
	proto.RegisterType((*DBInt32Value)(nil), "remoteDataAccess.DBInt32Value")
	proto.RegisterType((*DBInt64Collection)(nil), "remoteDataAccess.DBInt64Collection")
	proto.RegisterType((*DBInt64Value)(nil), "remoteDataAccess.DBInt64Value")
	proto.RegisterType((*DBSInt32Collection)(nil), "remoteDataAccess.DBSInt32Collection")
	proto.RegisterType((*DBSInt32Value)(nil), "remoteDataAccess.DBSInt32Value")
	proto.RegisterType((*DBSInt64Collection)(nil), "remoteDataAccess.DBSInt64Collection")
	proto.RegisterType((*DBSInt64Value)(nil), "remoteDataAccess.DBSInt64Value")
	proto.RegisterType((*DBUInt32Collection)(nil), "remoteDataAccess.DBUInt32Collection")
	proto.RegisterType((*DBUInt32Value)(nil), "remoteDataAccess.DBUInt32Value")
	proto.RegisterType((*DBUInt64Collection)(nil), "remoteDataAccess.DBUInt64Collection")
	proto.RegisterType((*DBUInt64Value)(nil), "remoteDataAccess.DBUInt64Value")
	proto.RegisterType((*DBSignedFixed32Collection)(nil), "remoteDataAccess.DBSignedFixed32Collection")
	proto.RegisterType((*DBSignedFixed32Value)(nil), "remoteDataAccess.DBSignedFixed32Value")
	proto.RegisterType((*DBSignedFixed64Collection)(nil), "remoteDataAccess.DBSignedFixed64Collection")
	proto.RegisterType((*DBSignedFixed64Value)(nil), "remoteDataAccess.DBSignedFixed64Value")
	proto.RegisterType((*DBBooleanCollection)(nil), "remoteDataAccess.DBBooleanCollection")
	proto.RegisterType((*DBBooleanValue)(nil), "remoteDataAccess.DBBooleanValue")
	proto.RegisterType((*DBStringCollection)(nil), "remoteDataAccess.DBStringCollection")
	proto.RegisterType((*DBStringValue)(nil), "remoteDataAccess.DBStringValue")
	proto.RegisterType((*DBBytesCollection)(nil), "remoteDataAccess.DBBytesCollection")
	proto.RegisterType((*DBBytesValue)(nil), "remoteDataAccess.DBBytesValue")
	proto.RegisterType((*DBDateTimeCollection)(nil), "remoteDataAccess.DBDateTimeCollection")
	proto.RegisterType((*DBDateTimeValue)(nil), "remoteDataAccess.DBDateTimeValue")
	proto.RegisterType((*DBFloatCollection)(nil), "remoteDataAccess.DBFloatCollection")
	proto.RegisterType((*DBFloatValue)(nil), "remoteDataAccess.DBFloatValue")
	proto.RegisterType((*DBDoubleCollection)(nil), "remoteDataAccess.DBDoubleCollection")
	proto.RegisterType((*DBDoubleValue)(nil), "remoteDataAccess.DBDoubleValue")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteDBServiceClient is the client API for RemoteDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteDBServiceClient interface {
	ExecuteNoneQuery(ctx context.Context, in *DbRequest, opts ...grpc.CallOption) (*DbResponse, error)
	ExecuteScalar(ctx context.Context, in *DbRequest, opts ...grpc.CallOption) (*DbResponse, error)
	ExecuteDataSet(ctx context.Context, in *DbRequest, opts ...grpc.CallOption) (*DbResponse, error)
}

type remoteDBServiceClient struct {
	cc *grpc.ClientConn
}

func NewRemoteDBServiceClient(cc *grpc.ClientConn) RemoteDBServiceClient {
	return &remoteDBServiceClient{cc}
}

func (c *remoteDBServiceClient) ExecuteNoneQuery(ctx context.Context, in *DbRequest, opts ...grpc.CallOption) (*DbResponse, error) {
	out := new(DbResponse)
	err := c.cc.Invoke(ctx, "/remoteDataAccess.RemoteDBService/ExecuteNoneQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteDBServiceClient) ExecuteScalar(ctx context.Context, in *DbRequest, opts ...grpc.CallOption) (*DbResponse, error) {
	out := new(DbResponse)
	err := c.cc.Invoke(ctx, "/remoteDataAccess.RemoteDBService/ExecuteScalar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteDBServiceClient) ExecuteDataSet(ctx context.Context, in *DbRequest, opts ...grpc.CallOption) (*DbResponse, error) {
	out := new(DbResponse)
	err := c.cc.Invoke(ctx, "/remoteDataAccess.RemoteDBService/ExecuteDataSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteDBServiceServer is the server API for RemoteDBService service.
type RemoteDBServiceServer interface {
	ExecuteNoneQuery(context.Context, *DbRequest) (*DbResponse, error)
	ExecuteScalar(context.Context, *DbRequest) (*DbResponse, error)
	ExecuteDataSet(context.Context, *DbRequest) (*DbResponse, error)
}

func RegisterRemoteDBServiceServer(s *grpc.Server, srv RemoteDBServiceServer) {
	s.RegisterService(&_RemoteDBService_serviceDesc, srv)
}

func _RemoteDBService_ExecuteNoneQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDBServiceServer).ExecuteNoneQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remoteDataAccess.RemoteDBService/ExecuteNoneQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDBServiceServer).ExecuteNoneQuery(ctx, req.(*DbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteDBService_ExecuteScalar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDBServiceServer).ExecuteScalar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remoteDataAccess.RemoteDBService/ExecuteScalar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDBServiceServer).ExecuteScalar(ctx, req.(*DbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteDBService_ExecuteDataSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteDBServiceServer).ExecuteDataSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remoteDataAccess.RemoteDBService/ExecuteDataSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteDBServiceServer).ExecuteDataSet(ctx, req.(*DbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteDBService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remoteDataAccess.RemoteDBService",
	HandlerType: (*RemoteDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteNoneQuery",
			Handler:    _RemoteDBService_ExecuteNoneQuery_Handler,
		},
		{
			MethodName: "ExecuteScalar",
			Handler:    _RemoteDBService_ExecuteScalar_Handler,
		},
		{
			MethodName: "ExecuteDataSet",
			Handler:    _RemoteDBService_ExecuteDataSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dataRequest.proto",
}

func init() { proto.RegisterFile("dataRequest.proto", fileDescriptor_dataRequest_b9e3e327626b2af9) }

var fileDescriptor_dataRequest_b9e3e327626b2af9 = []byte{
	// 1175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x98, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xc7, 0xa7, 0x24, 0x76, 0xe2, 0xe3, 0xb8, 0x49, 0xb8, 0xa0, 0x70, 0xb2, 0x60, 0xcd, 0xb4,
	0xaf, 0x60, 0xc3, 0xdc, 0x21, 0x09, 0xb2, 0xaf, 0x22, 0x40, 0xdc, 0xb4, 0x45, 0xb0, 0x65, 0x4d,
	0xe9, 0xb8, 0xc0, 0xd0, 0x2b, 0x5a, 0xa6, 0x3d, 0x61, 0xb6, 0xe8, 0x8a, 0x54, 0x13, 0xef, 0x7a,
	0x18, 0xb6, 0x67, 0xd8, 0xa3, 0xed, 0x61, 0x36, 0x90, 0x92, 0x62, 0x91, 0xa2, 0x3c, 0x79, 0xbd,
	0x0b, 0x0f, 0xcf, 0xf9, 0xeb, 0xe7, 0x3f, 0xa9, 0x43, 0x2a, 0xb0, 0xd5, 0x27, 0x82, 0x60, 0xfa,
	0x3a, 0xa2, 0x5c, 0xb4, 0x26, 0x21, 0x13, 0x0c, 0x6d, 0x86, 0x74, 0xcc, 0x04, 0x3d, 0x27, 0x82,
	0x9c, 0x79, 0x1e, 0xe5, 0x7c, 0x77, 0x67, 0xc8, 0xd8, 0x70, 0x44, 0x1f, 0xaa, 0xf9, 0x5e, 0x34,
	0x78, 0x48, 0x82, 0x69, 0x9c, 0xbc, 0xfb, 0xc0, 0x9c, 0x12, 0xfe, 0x98, 0x72, 0x41, 0xc6, 0x93,
	0x38, 0xc1, 0xfd, 0xcb, 0x81, 0xda, 0x79, 0x2f, 0x79, 0x02, 0xda, 0x86, 0x8a, 0x60, 0xbf, 0xd0,
	0xa0, 0xe9, 0xec, 0x3b, 0x07, 0x35, 0x1c, 0x0f, 0xd0, 0x23, 0x00, 0x4e, 0xc3, 0x37, 0x34, 0xbc,
	0x08, 0x06, 0xac, 0xb9, 0xb4, 0xef, 0x1c, 0xd4, 0x0f, 0xf7, 0x5a, 0x26, 0x46, 0xab, 0x73, 0x97,
	0x83, 0x33, 0xf9, 0xe8, 0x3e, 0x54, 0xb9, 0x17, 0xfa, 0x13, 0xd1, 0x5c, 0x56, 0xa2, 0xc9, 0x08,
	0xb9, 0xb0, 0xce, 0x5f, 0x8f, 0x3a, 0x82, 0x08, 0x3a, 0xa6, 0x81, 0x68, 0xae, 0xa8, 0x59, 0x2d,
	0xe6, 0xfe, 0xe1, 0x00, 0x74, 0x74, 0x29, 0x35, 0x4a, 0xf8, 0x92, 0x11, 0x42, 0xb0, 0x32, 0x61,
	0xa1, 0x50, 0x68, 0x15, 0xac, 0xfe, 0x46, 0xbb, 0xb0, 0x26, 0xbd, 0xeb, 0x11, 0x4e, 0x93, 0x07,
	0xdf, 0x8d, 0xa5, 0x4e, 0xc4, 0x69, 0x78, 0xd1, 0x4f, 0x1e, 0x9a, 0x8c, 0x64, 0xcd, 0x84, 0x70,
	0x7e, 0xc3, 0xc2, 0x7e, 0xb3, 0x12, 0xd7, 0xa4, 0x63, 0xf7, 0x6f, 0x07, 0x40, 0x1a, 0xc5, 0x27,
	0x2c, 0xe0, 0x14, 0xed, 0x41, 0x8d, 0x47, 0x9e, 0x47, 0x69, 0x9f, 0xf6, 0x15, 0xcd, 0x1a, 0x9e,
	0x05, 0x50, 0x13, 0x56, 0xc7, 0x94, 0x73, 0x32, 0xa4, 0x8a, 0xa9, 0x86, 0xd3, 0x21, 0x3a, 0x85,
	0x3a, 0xf7, 0xc8, 0x88, 0x84, 0x2f, 0xc9, 0x28, 0x8a, 0xc9, 0xac, 0x66, 0x9e, 0xb7, 0xcf, 0x82,
	0xa9, 0xca, 0xc1, 0xd9, 0x02, 0xb4, 0x0f, 0xf5, 0x90, 0xdd, 0x3c, 0x19, 0x0c, 0xa8, 0x27, 0x68,
	0xcc, 0x5f, 0xc1, 0xd9, 0x10, 0x3a, 0x82, 0x55, 0xf9, 0x43, 0x39, 0x15, 0xea, 0x37, 0xd4, 0x0f,
	0x77, 0x2c, 0xea, 0x44, 0x90, 0x0e, 0x15, 0x38, 0xcd, 0x74, 0x4f, 0x61, 0x35, 0x89, 0xa1, 0x23,
	0xa8, 0x0a, 0xd2, 0x1b, 0x51, 0xde, 0x74, 0xf6, 0x97, 0x0f, 0xea, 0x87, 0xef, 0xd9, 0xcb, 0xaf,
	0x65, 0x0e, 0x4e, 0x52, 0xdd, 0xdf, 0xe5, 0x36, 0x4a, 0xa3, 0x72, 0x3d, 0x02, 0x32, 0xa6, 0xc9,
	0x2a, 0xa9, 0xbf, 0xd1, 0x09, 0xac, 0x7a, 0x6c, 0x14, 0x8d, 0x03, 0xde, 0x5c, 0x52, 0xba, 0x7b,
	0x76, 0xdd, 0xc7, 0x2a, 0x09, 0xa7, 0xc9, 0xe8, 0x0b, 0x58, 0x09, 0xd9, 0x0d, 0x6f, 0x2e, 0xab,
	0xa2, 0x82, 0xdf, 0x82, 0xd9, 0x0d, 0x56, 0x69, 0xee, 0x6f, 0x72, 0x99, 0xee, 0x64, 0xac, 0x24,
	0xf7, 0xa1, 0xda, 0xef, 0x5d, 0x4f, 0x27, 0xe9, 0xbe, 0x48, 0x46, 0x71, 0xbc, 0xe3, 0xff, 0x4a,
	0x13, 0x57, 0x93, 0x91, 0x5c, 0xea, 0x49, 0x48, 0x3d, 0x9f, 0xfb, 0x2c, 0x50, 0x96, 0x56, 0xf0,
	0x2c, 0x20, 0x5f, 0x19, 0x3f, 0xe8, 0xd3, 0xdb, 0x66, 0x55, 0xcd, 0xc4, 0x03, 0xf7, 0xcf, 0x5a,
	0x6c, 0x28, 0x66, 0x37, 0xe8, 0x15, 0x20, 0x3e, 0xf0, 0x6f, 0x69, 0xff, 0xe8, 0xf0, 0x31, 0x1b,
	0x8d, 0xa8, 0x27, 0xa4, 0x90, 0xa3, 0xd6, 0xe6, 0x73, 0xdb, 0xca, 0x77, 0xfc, 0x61, 0x40, 0xfb,
	0x4f, 0xcd, 0x12, 0x6c, 0x91, 0x99, 0x89, 0x9f, 0x1c, 0x67, 0xc4, 0x97, 0x4a, 0x89, 0x67, 0x4b,
	0xb0, 0x45, 0x06, 0x75, 0x60, 0xab, 0xc7, 0xd8, 0x88, 0x92, 0x20, 0xa3, 0x1d, 0x6f, 0xd9, 0x8f,
	0x6d, 0xda, 0x6d, 0x33, 0x19, 0xe7, 0xeb, 0xd1, 0x15, 0x6c, 0x72, 0x11, 0xfa, 0xc1, 0x30, 0xa3,
	0xb9, 0xa2, 0x34, 0x3f, 0xb2, 0xf2, 0x1a, 0xb9, 0x38, 0x57, 0xad, 0x14, 0xfd, 0x40, 0x68, 0xf6,
	0x56, 0xe6, 0x28, 0x5e, 0xe8, 0xb9, 0x38, 0x57, 0x9d, 0x2a, 0x6a, 0x9e, 0x56, 0xe7, 0x2b, 0x6a,
	0x66, 0xe6, 0xaa, 0xa5, 0x62, 0x64, 0x32, 0xae, 0x16, 0x2b, 0x76, 0x73, 0x8c, 0x91, 0x85, 0x31,
	0x32, 0x19, 0xd7, 0xe6, 0x2b, 0xea, 0x8c, 0x66, 0x35, 0xba, 0x84, 0x0d, 0x13, 0xb1, 0xa6, 0x04,
	0x3f, 0xb4, 0x09, 0x9a, 0x84, 0x66, 0x6d, 0x22, 0xa7, 0xf1, 0xc1, 0x5c, 0x39, 0x0d, 0x6f, 0xc3,
	0x42, 0xd7, 0x9b, 0x0a, 0xca, 0x33, 0x72, 0xf5, 0x62, 0xb9, 0xb6, 0x9e, 0x8a, 0xcd, 0x5a, 0x29,
	0x37, 0x18, 0x31, 0x22, 0x32, 0x72, 0xeb, 0xc5, 0x72, 0x4f, 0xf5, 0x54, 0x6c, 0xd6, 0xca, 0xd5,
	0xe8, 0xb3, 0xa8, 0x37, 0xa2, 0x19, 0xbd, 0x46, 0xf1, 0x6a, 0x9c, 0x1b, 0xb9, 0x38, 0x57, 0x8d,
	0x9e, 0x41, 0x83, 0x04, 0xd3, 0x8c, 0xdc, 0x3d, 0x25, 0xf7, 0x41, 0xc1, 0x59, 0x91, 0xd1, 0xd2,
	0xeb, 0xdc, 0x67, 0xb0, 0x61, 0x64, 0xa0, 0x63, 0xa8, 0xbe, 0x91, 0xc7, 0x49, 0xda, 0xe3, 0xe7,
	0x1f, 0x40, 0x49, 0xae, 0xfb, 0x12, 0x60, 0x16, 0x95, 0x6d, 0x51, 0xc5, 0x55, 0x27, 0x8d, 0xfb,
	0xeb, 0x2c, 0x80, 0x3e, 0x83, 0x8a, 0x1a, 0x24, 0xad, 0x68, 0xbb, 0x15, 0x5f, 0x44, 0x5a, 0xe9,
	0x45, 0xa4, 0x75, 0x16, 0x4c, 0x71, 0x9c, 0xe2, 0x7e, 0x0f, 0x5b, 0xb9, 0xed, 0x84, 0x4e, 0x0c,
	0xc4, 0xf7, 0x0b, 0xf7, 0xa0, 0x0e, 0xf9, 0x2d, 0xac, 0x67, 0xe3, 0xb3, 0xfe, 0xec, 0x64, 0xfa,
	0xb3, 0x8c, 0xce, 0xf0, 0x2a, 0x26, 0x88, 0xb6, 0xef, 0xca, 0x82, 0x9c, 0x1c, 0xdb, 0x41, 0x92,
	0x78, 0x19, 0x90, 0xe5, 0x14, 0xe4, 0x12, 0x50, 0xbe, 0x4f, 0xa1, 0xaf, 0x0c, 0x92, 0x07, 0xc5,
	0xdd, 0x4d, 0x47, 0xf9, 0x0e, 0x1a, 0xda, 0x44, 0x19, 0x96, 0xad, 0x1c, 0x8b, 0xe6, 0x4a, 0x69,
	0x16, 0xd3, 0x96, 0x3b, 0x96, 0x05, 0x7c, 0x41, 0x1a, 0x4b, 0xf7, 0x7f, 0xf9, 0xd2, 0x2d, 0xf2,
	0xa5, 0xbb, 0x98, 0x2f, 0x8d, 0x1c, 0xcb, 0xe2, 0xbe, 0x74, 0x8b, 0x7c, 0xe9, 0x2e, 0xe6, 0xcb,
	0x4a, 0xca, 0xf2, 0x0a, 0x76, 0x0a, 0xaf, 0x0d, 0xe8, 0xd4, 0x40, 0xfa, 0xe4, 0x3f, 0xef, 0x1c,
	0x3a, 0x59, 0x1b, 0xb6, 0x6d, 0xf3, 0x65, 0x00, 0x37, 0x8a, 0x00, 0x35, 0xcf, 0x16, 0x05, 0x34,
	0xad, 0x33, 0x01, 0x17, 0x70, 0x70, 0x33, 0x05, 0x7c, 0x0e, 0xef, 0x5a, 0xee, 0x2f, 0xe8, 0x6b,
	0x03, 0x6d, 0x7f, 0xce, 0xb5, 0x47, 0x87, 0x7a, 0x04, 0xf7, 0xf4, 0x99, 0x32, 0x38, 0x6b, 0xfa,
	0x4b, 0x67, 0x5e, 0x74, 0xca, 0xbd, 0x74, 0xaa, 0xca, 0xf6, 0xd2, 0xcd, 0x26, 0xca, 0xb0, 0xd4,
	0xb4, 0xae, 0x68, 0x9c, 0xa7, 0xe5, 0xba, 0xa2, 0x2a, 0xb2, 0x74, 0xc5, 0x59, 0xbc, 0x0c, 0xc8,
	0x7a, 0x0a, 0xf2, 0x42, 0xae, 0xf3, 0x39, 0x11, 0xf4, 0xda, 0x1f, 0x67, 0x4f, 0xca, 0x6f, 0x0c,
	0x16, 0xeb, 0x11, 0x99, 0xd6, 0xe9, 0x38, 0x3f, 0xc9, 0xb3, 0x51, 0x9b, 0x2a, 0x20, 0xfa, 0x52,
	0x3f, 0xcf, 0x76, 0x73, 0xe7, 0xd9, 0x75, 0xfa, 0x61, 0xad, 0xd9, 0x66, 0xdc, 0x1b, 0xca, 0xd9,
	0xa6, 0x8a, 0x2c, 0xb6, 0xcd, 0xe2, 0x65, 0x6c, 0x5b, 0xd2, 0xf6, 0x92, 0x79, 0xe1, 0x28, 0xb7,
	0x97, 0xe2, 0x2a, 0xcb, 0x5e, 0xca, 0x4c, 0x94, 0x61, 0x71, 0x12, 0x96, 0xc3, 0x7f, 0x1c, 0xd8,
	0xc0, 0xf1, 0x73, 0xda, 0xf2, 0xc3, 0xde, 0xf7, 0x28, 0x7a, 0x0e, 0x9b, 0x4f, 0x6e, 0xa9, 0x17,
	0x09, 0xfa, 0x23, 0x0b, 0xe8, 0x8b, 0x88, 0x86, 0x53, 0x64, 0xfb, 0xe8, 0x4c, 0xff, 0x4b, 0xb1,
	0xbb, 0x67, 0x9f, 0x8c, 0xbf, 0xcc, 0xdd, 0x77, 0xd0, 0x0f, 0xd0, 0x48, 0x04, 0x3b, 0xea, 0xcb,
	0xf9, 0xed, 0xd4, 0x2e, 0xe1, 0x5e, 0xa2, 0x96, 0x7e, 0x21, 0xbf, 0x8d, 0x5c, 0xfb, 0x53, 0x68,
	0x0c, 0x7c, 0xfe, 0x73, 0x6b, 0x18, 0x4e, 0xbc, 0x56, 0xd8, 0x27, 0xed, 0x6d, 0xc3, 0x8f, 0x2b,
	0xb9, 0xa3, 0xae, 0x9c, 0x5e, 0x55, 0x6d, 0xad, 0xa3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2b,
	0xfe, 0x6f, 0xde, 0x03, 0x12, 0x00, 0x00,
}
